services:
  postgres:
    image: postgres:16
    container_name: vicsmath_postgres
    restart: always
    environment:
      POSTGRES_USER: vicsadmin
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: vicsmath
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: vicsmath_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vicsmath.com
      PGADMIN_DEFAULT_PASSWORD: strongpassword123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

