services:
  postgres:
    image: postgres:15
    container_name: vics-postgres
    environment:
      POSTGRES_DB: vicsmath
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - vicsmath_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: vicsmath_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  vicsmath_data:
